### ISSUE TITLE
Hỏi về pretrained model?

### ISSUE THREAD

**Issue by dang3tion** [v-nhandt21/ViSV2TTS#3]
Xin chào anh, hiện em đang triển khai ứng dụng phát thanh nội bộ chuyển văn bản thành giọng nói tại đơn vị, không biết em có thể xin pretrained model của mô hình clone voice này không, vì hiện tại em đang tìm kiếm giọng nói phù hợp cho phát thanh nhưng các tập dữ liệu mở trên mạng lại không có, mà vấn đề trained tốn rất nhiều thời gian cho hạn của ứng dụng này, mục đích xây dựng ứng dụng này không mang tính thương mại, không biết ý kiến anh ntn?

**Comment by kingkong135** [comment]
@dang3tion trên mạng không có một số public model đó bạn ví dụng anh này đã public ít nhất 3 model về TTS: 

https://huggingface.co/spaces/ntt123/Vietnam-male-voice-TTS

**Comment by dang3tion** [comment]
Mình cũng có áp dụng rồi, nhưng hiện tại đơn vị muốn có thêm một số giọng khác cho phù hợp với việc đọc phát thanh, đơn vị mình làm thuộc cơ quan nhà nước.
